import type { Metadata } from "next";
import {
  Kumbh_Sans,
  Figtree,
  Chivo,
  Rajdhani,
  Raleway,
  Mulish,
  Pattaya,
  Recursive,
  Gantari,
  Overpass_Mono,
} from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Portfolio fonts:

const kumbhSans = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

// PROJECT: inquiryon

const chivo = Chivo({
  variable: "--font-inquiryon-header",
  subsets: ["latin"],
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

// just for the logo
const rajdhani = Rajdhani({
  variable: "--font-inquiryon-logo",
  subsets: ["latin"],
  weight: "600",
});

// PROJECT: concaly

const raleway = Raleway({
  variable: "--font-concaly-header",
  subsets: ["latin"],
});

// NOTE: mulish for body

// logo
const pattaya = Pattaya({
  variable: "--font-concaly-logo",
  subsets: ["latin"],
  weight: "400",
});

// PROJECT: Mudboard

const headerFont = Recursive({
  variable: "--font-mudboard-header",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const bodyFont = Gantari({
  variable: "--font-mudboard-body",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const monoFont = Overpass_Mono({
  variable: "--font-mudboard-mono",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${kumbhSans.variable}
        ${figtree.variable}
        ${chivo.variable}
        ${mulish.variable}
        ${rajdhani.variable}
        ${raleway.variable}
        ${pattaya.variable}
        ${headerFont.variable}
        ${bodyFont.variable}
        ${monoFont.variable}
        antialiased
      `}
      >
        {children}
      </body>
    </html>
  );
}
